// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxxrjrfmrrrwhwzkjxdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4eHJqcmZtcnJyd2h3emtqeGR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjI5OTEsImV4cCI6MjA2MjczODk5MX0.8Bc7iWymN9vgzmci9e-9I2PubS_JBMrQVlLDt9cLwoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);